spring:
  jwt:
    secret: 12345678901234567890123456789012
  datasource:
    hikari:
      primary:
        jdbc-url: 
        username:
        password:
        driver-class-name: org.mariadb.jdbc.Driver
      secondary:
        jdbc-url:
        username:
        password:
        driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true


logging:
  level:
    org.hibernate.SQL: debug



