spring:
  datasource:
    url: ${DBURL}
    username: ${DBUSERNAME}
    password: ${DBPASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug

