server:
  port: 8000

spring:
  jwt:
    secret: ${JWT_SECRET}
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: member-api
          uri: lb://member-api
          predicates:
            - Path=/member/**
        - id: post-api
          uri: lb://post-api
          predicates:
            - Path=/post/**
          filters:
            - JwtFilter
eureka:
  client:
    service-url:
      defaultZone: http://192.168.0.124:8001/eureka/
    registerWithEureka: true
    fetchRegistry: true