spring:
  datasource:
    url: jdbc:mariadb://192.168.141.100:3306/day02
    username: sje
    password: qwer1234
    driver-class-name: org.mariadb.jdbc.Driver

#spring:
#  datasource:
#    url: ${DBURL}
#    username: ${DBUSERNAME}
#    password: ${DBUSERPASSWORD}
#    driver-class-name: org.mariadb.jdbc.Driver